In [1]:
import numpy as np
# 같은 자료형 으로만 만드는 numpy배열

data1 = [1, 1, 2, 3, '4', 5]
a1 = np.array(data1)

In [3]:
a1

array(['1', '1', '2', '3', '4', '5'], dtype='<U11')

In [5]:
type(a1)

numpy.ndarray

In [7]:
type(data1)

list

## Numpy 는 파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지
-   다차원 배열 데이터를 효과적으로 처리 가능

In [7]:
import numpy as np

data1 =  [0, 1, 2, 3, 4, 5]
#print(data1*2)    # [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
print(a1*2) # [ 0  2  4  6  8 10]

[ 0  2  4  6  8 10]


In [16]:
a1.dtype

dtype('int32')

In [18]:
a2 = np.array([0.1, 5, 4, 12, 0.5])  
a2.dtype

dtype('float64')

### 시퀀스 데이터로부터 배열 생성

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
b1 = np.arange(12).reshape(4,3)

In [24]:
b1.shape   #  중요 Numpy 2차원 배열  (m, n)  m X n 행렬 구조

(4, 3)

In [26]:
np.linspace(1, 10, 10)   #1 부터 10까지(10포함) 10개의 데이터를 생성해줘 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 특별한 형태의 배열 생성 함수
- full,  ones, zeros

In [30]:
array1 = np.full(6, 1)  # 1 로 6개짜리  넘파일 배열을 만들어줘

In [32]:
print(array1)

[1 1 1 1 1 1]


In [34]:
array2 = np.ones(6)  # 1 로 6개짜리  넘파일 배열을 만들어줘
print(array2)

[1. 1. 1. 1. 1. 1.]


In [36]:
array3 = np.zeros(6)
print(array3)

[0. 0. 0. 0. 0. 0.]


In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# 단위 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 배열 의 데이터 타입 변환

In [43]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])
# dtype='<U8'  유니코드이며 문자의 수 최대 8개

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [45]:
str_a1 = np.array(['1.5', '0.62', '2', '3.14', '3.141592'])
num_a1 = str_a1.astype(float)
num_a1.dtype

dtype('float64')

In [47]:
num_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

In [49]:
str_a1.dtype

dtype('<U8')

In [52]:
# 랜덤 함수 이용해서 3차원배열
np.random.rand(2, 3, 4)  # 2면 3행 4열

array([[[0.59329353, 0.62411504, 0.23367316, 0.21286504],
        [0.30515913, 0.4700361 , 0.18634157, 0.27560079],
        [0.30552908, 0.23190655, 0.97897624, 0.77994524]],

       [[0.91536995, 0.59697181, 0.71195055, 0.70201154],
        [0.74803768, 0.35957459, 0.98217125, 0.25995364],
        [0.61529867, 0.46793727, 0.55941084, 0.97279711]]])

In [54]:
np.random.randint(10, size=(3,4))

array([[5, 0, 3, 5],
       [7, 5, 7, 4],
       [0, 0, 6, 0]])

In [56]:
np.random.randint(1,30)

25

# 배열의 연산
- 기본 연산

In [59]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1,   2,  3,  4])
arr1 * 2

array([20, 40, 60, 80])

In [61]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [63]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [65]:
# bool 연산 : 중요
arr1 > 20

array([False, False,  True,  True])

- 통계를 위한 연산

In [68]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [70]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [72]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [74]:
[arr3.min(), arr3.max()]

[0, 4]

In [76]:
arr3.cumsum()

array([ 0,  1,  3,  6, 10])

In [82]:
# numpy 행렬 연산
A = np.array([0, 1, 2, 3]).reshape(2,2)
B = np.array([3, 2, 1, 0]).reshape(2,2) 
A


array([[0, 1],
       [2, 3]])

In [84]:
B

array([[3, 2],
       [1, 0]])

In [86]:
# 행렬곱        가로 * 세로   1 = (0 * 3) + (1 * 1) 
A.dot(B)

array([[1, 0],
       [9, 4]])

In [88]:
# 전치행렬 
A.transpose()

array([[0, 2],
       [1, 3]])

In [90]:
np.linalg.inv(A)   # 역행렬      | a 0     b 1|                                  
#                                | c 2    d 3|      ( 1  / a*d - b*c ) = -0.5        | 3  -1 |  |  d  -b   |   
                                    #                  행렬식 (  a*d - b*c )          |-2  0 |  |  -c   a  |

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [92]:
np.linalg.det(A)   # 행렬식

-2.0

### 배열의 인덱싱과 슬라이싱  (활용도 높음 : 매우중요)
- 인덱싱 : 위치나 조건을 지정해 배열의 원소를 선택하는것
- 슬라이싱 : 범위 지정해 배열의 원소를 선택하는것

In [96]:
a1 = np.array([0, 10, 20, 30, 40, 50 ])

In [98]:
a1[4]

40

In [100]:
# 중요
a1[[1, 3, 4]]

array([10, 30, 40])

In [104]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [106]:
# 중요
a2[0, 1]

20

In [108]:
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [110]:
a2[1]

array([40, 50, 60])

In [112]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [114]:
# 행렬에서 여러개   쉼표앞에  행,   뒤 열  array([10, 80])
a2[ [0, 2], [0, 1] ]  #  0행 0열,  2행 1열

array([10, 80])

In [116]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [118]:
print(b2[0:2, 1:3])

[[20 30]
 [50 60]]


In [120]:
print(b2[:, 1:3])   # 활용도 중요

[[20 30]
 [50 60]
 [80 90]]


In [122]:
from timeit import timeit
# 파이썬 리스트 연산
y = list(range(100000000)) # [0, 1, 2, ....... 99999999]
timeit( lambda: [ n*2 for n in y], number=1 ) # 함수를 1번만 실행

5.360783700016327

In [124]:
x = np.arange(100000000)  # nd.array[0, 1, 2, ....... 99999999]
timeit( lambda: x*2, number=1)

0.1402152000227943

# 구조적 데이터 표시와 처리에 강한 pandas
 - 구조적 데이터 생성
 - Series 를 활용한 데이터 생성

In [129]:
import pandas as pd

In [131]:
s1 = pd.Series([10, 20, 30, 40, 50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [133]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [135]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [137]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [139]:
s3 = pd.Series([np.nan, 10, 30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [141]:
index_date = ['2024-08-27', '2024-08-28', '2024-08-29', '2024-08-30']
s4 = pd.Series([200, 195, np.nan, 205], index=index_date)
s4

2024-08-27    200.0
2024-08-28    195.0
2024-08-29      NaN
2024-08-30    205.0
dtype: float64

In [143]:
s5 = pd.Series({'국어': 100, '영어': 95, '수학':90})
s5

국어    100
영어     95
수학     90
dtype: int64

In [149]:
pd.date_range(start='08/26/2024', end='2024.08.31') #  인덱스 end값 포함

DatetimeIndex(['2024-08-26', '2024-08-27', '2024-08-28', '2024-08-29',
               '2024-08-30', '2024-08-31'],
              dtype='datetime64[ns]', freq='D')

In [151]:
pd.date_range(start='2024/08/30', periods = 24, freq = 'H')

C:\Users\Kosmo\AppData\Local\Temp\ipykernel_14712\4294923003.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start='2024/08/30', periods = 24, freq = 'H')


DatetimeIndex(['2024-08-30 00:00:00', '2024-08-30 01:00:00',
               '2024-08-30 02:00:00', '2024-08-30 03:00:00',
               '2024-08-30 04:00:00', '2024-08-30 05:00:00',
               '2024-08-30 06:00:00', '2024-08-30 07:00:00',
               '2024-08-30 08:00:00', '2024-08-30 09:00:00',
               '2024-08-30 10:00:00', '2024-08-30 11:00:00',
               '2024-08-30 12:00:00', '2024-08-30 13:00:00',
               '2024-08-30 14:00:00', '2024-08-30 15:00:00',
               '2024-08-30 16:00:00', '2024-08-30 17:00:00',
               '2024-08-30 18:00:00', '2024-08-30 19:00:00',
               '2024-08-30 20:00:00', '2024-08-30 21:00:00',
               '2024-08-30 22:00:00', '2024-08-30 23:00:00'],
              dtype='datetime64[ns]', freq='h')

In [153]:
# 마일스톤 : 진행과정에서 중요한 목표나 단계 ( 기획, 개발, 테스트 )
#  개발단계: 게이트(특정 조건을 충족 해야하는것, 허들) 명확히 해야함
#  목표: 최종목표를 달성하기 위한 목표 정해야함

In [155]:
import pandas as pd

In [157]:
pd.DataFrame([ [1,2,3], [4,5,6], [7,8,9] ])
# 데이터프레임 생성문법
# df = pd.DataFrame(data [, index = index_data, columns = columns_data ])   #[]옵션

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [161]:
index_date = pd.date_range('2024-09-02', periods=4)
colmns_list = ['A', 'B', 'C']
data = np.array([ [1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
pd.DataFrame(data, index=index_date, columns=colmns_list)

A   B   C
2024-09-02   1   2   3
2024-09-03   4   5   6
2024-09-04   7   8   9
2024-09-05  10  11  12

In [165]:

table_data = { "연도": [2020, 2021, 2021, 2022, 2022],
               "지사": ['한국', '한국', '미국', '한국', '미국'],
               "고객 수": [200, 250, 450, 300, 500] }
type(table_data)

dict

In [167]:
# 딕셔너리 데이터를 데이터 프레임 - 키 값이 컬럼 이됨
df = pd.DataFrame(table_data)
df

연도  지사  고객 수
0  2020  한국   200
1  2021  한국   250
2  2021  미국   450
3  2022  한국   300
4  2022  미국   500

In [169]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [171]:
df.columns

Index(['연도', '지사', '고객 수'], dtype='object')

In [173]:
df.values

array([[2020, '한국', 200],
       [2021, '한국', 250],
       [2021, '미국', 450],
       [2022, '한국', 300],
       [2022, '미국', 500]], dtype=object)

### pandas 데이터 연산

In [176]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([10,20,30,40,50])
s2 * s1

0     10.0
1     40.0
2     90.0
3    160.0
4      NaN
dtype: float64

In [178]:
table_data1 = { 'A': [1,2,3,4,5],
                'B': [10,20,30,40,50],
                'C': [100,200,300,400,500] }
df1 = pd.DataFrame(table_data1)
df1

A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [180]:
table_data2 =  { 'A': [6,7,8],
                'B': [60,70,80],
                'C': [600,700,800] }
df2 = pd.DataFrame(table_data2)
df2

A   B    C
0  6  60  600
1  7  70  700
2  8  80  800

In [182]:
df1 + df2

A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN

In [186]:
# 계절별 강수량 (단위 : mm)  - pandas 메서드 통계 분석하는 방법
table_data3 = { '봄' : [256.5, 264.3, 215.9, 223.2, 312.8],
               '여름' : [770.6, 567.5, 599.8, 387.1, 446.2],
               '가을' : [363.5, 231.2, 293.1, 247.7, 381.6],
               '겨울' : [139.3, 59.9, 76.9, 109.1, 108.1] }
columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']
df3 = pd.DataFrame(table_data3, index=index_list, columns = columns_list )
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [190]:
df3.std(axis=0)

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [192]:
df3.std(axis=1)

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

In [194]:
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

# 2011년부터 2017년까지 노선별 KTX 이용자 수

In [197]:
import pandas as pd
import numpy as np
KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선 KTX': [np.nan, np.nan, np.nan, np.nan, 2395, 3786, 6667]}

col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']

df_KTX = pd.DataFrame(KTX_data, columns= col_list, index= index_list)
df_KTX



경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [203]:
df_KTX.head()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [205]:
df_KTX.tail()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [207]:
df_KTX.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 2011 to 2017
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   경부선 KTX  7 non-null      int64  
 1   호남선 KTX  7 non-null      int64  
 2   경전선 KTX  7 non-null      int64  
 3   전라선 KTX  7 non-null      int64  
 4   동해선 KTX  3 non-null      float64
dtypes: float64(1), int64(4)
memory usage: 336.0+ bytes


In [211]:
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [213]:
df_KTX[4:7]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [215]:
## loc   - 인덱스명   -- 행
df_KTX.loc['2017']

경부선 KTX    32427.0
호남선 KTX     9228.0
경전선 KTX     5570.0
전라선 KTX     5766.0
동해선 KTX     6667.0
Name: 2017, dtype: float64

In [217]:
df_KTX.iloc[6] - 행의 인덱스

경부선 KTX    32427.0
호남선 KTX     9228.0
경전선 KTX     5570.0
전라선 KTX     5766.0
동해선 KTX     6667.0
Name: 2017, dtype: float64

In [219]:
df_KTX['경부선 KTX']

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선 KTX, dtype: int64

In [221]:
df_KTX['경부선 KTX']['2012':'2014']  # 인덱스명  STOP포함

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64

In [225]:
df_KTX['경부선 KTX'][1:4]   # 인덱스 슬라이싱  STOP - 1

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64

In [227]:
df_KTX.loc["2017"]['호남선 KTX']

9228.0

In [229]:
df_KTX['호남선 KTX'].loc["2017"]

9228

In [268]:
df_KTX.loc['2017', '호남선 KTX']    # df.loc[row, column]

9228

In [231]:
df_KTX.T

2011     2012     2013     2014     2015     2016     2017
경부선 KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41266.0  32427.0
호남선 KTX   7313.0   6967.0   6873.0   6626.0   8675.0  10622.0   9228.0
경전선 KTX   3627.0   4168.0   4088.0   4424.0   4606.0   4984.0   5570.0
전라선 KTX    309.0   1771.0   1954.0   2244.0   3146.0   3945.0   5766.0
동해선 KTX      NaN      NaN      NaN      NaN   2395.0   3786.0   6667.0

In [233]:
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

## 세로 방향으로 통합하기

In [236]:
df1 = pd.DataFrame({'Class1': [95, 92, 98, 100],
                    'Class2': [91, 93, 97, 99]} )
df1

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99

In [240]:
df2 = pd.DataFrame({'Class1': [87, 89],
                    'Class2': [85, 90] })
df2

Class1  Class2
0      87      85
1      89      90

In [250]:
# df_combined = df1.append(df2)   # deprecated

In [254]:
df_combined = pd.concat([df1, df2], ignore_index=True)
df_combined

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
4      87      85
5      89      90

In [256]:
df4 = pd.DataFrame({'Class3': [93,91,95,98]})
df4

Class3
0      93
1      91
2      95
3      98

In [258]:
df1.join(df4)

Class1  Class2  Class3
0      95      91      93
1      92      93      91
2      98      97      95
3     100      99      98

### 특정 열을 기준으로 통합하기


In [271]:
df_A_B  = pd.DataFrame({ '판매월': ['1월', '2월', '3월', '4월'],
                         '제품A': [100, 150, 200, 130],
                        '제품B': [90, 110, 140, 170]} )
df_A_B

판매월  제품A  제품B
0  1월  100   90
1  2월  150  110
2  3월  200  140
3  4월  130  170

In [273]:
df_C_D  = pd.DataFrame({ '판매월': ['1월', '2월', '3월', '4월'],
                         '제품C': [112, 141, 203, 134],
                        '제품D': [90, 110, 140, 170]} )
df_C_D

판매월  제품C  제품D
0  1월  112   90
1  2월  141  110
2  3월  203  140
3  4월  134  170

In [275]:
df_A_B.merge(df_C_D)

판매월  제품A  제품B  제품C  제품D
0  1월  100   90  112   90
1  2월  150  110  141  110
2  3월  200  140  203  140
3  4월  130  170  134  170

In [277]:
%%writefile  D:\DEV\myPyCode\data\sea_rain.csv
연도,동해,남해,서해,전체
1996,17.4629,17.2288,14.436,15.9067
1997,17.4116,17.4092,14.8248,16.1526
1998,17.5944,18.011,15.2512,16.6044
1999,18.1495,18.3175,14.8979,16.6284
2000,17.9288,18.1766,15.0504,16.6178

Writing D:\DEV\myPyCode\data\sea_rain.csv


In [279]:
!type D:\DEV\myPyCode\data\sea_rain.csv

�뿰�룄,�룞�빐,�궓�빐,�꽌�빐,�쟾泥�
1996,17.4629,17.2288,14.436,15.9067
1997,17.4116,17.4092,14.8248,16.1526
1998,17.5944,18.011,15.2512,16.6044
1999,18.1495,18.3175,14.8979,16.6284
2000,17.9288,18.1766,15.0504,16.6178


In [285]:
import pandas as pd
pd.read_csv('D:\DEV\myPyCode\data\sea_rain.csv', encoding="utf-8")

<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Kosmo\AppData\Local\Temp\ipykernel_14712\2663259996.py:2: SyntaxWarning: invalid escape sequence '\D'
  pd.read_csv('D:\DEV\myPyCode\data\sea_rain.csv', encoding="utf-8")


연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [287]:
%%writefile  D:\DEV\myPyCode\data\sea_rain_space.csv
연도 동해 남해 서해 전체
1996 17.4629 17.2288 14.436 15.9067
1997 17.4116 17.4092 14.8248 16.1526
1998 17.5944 18.011 15.2512 16.6044
1999 18.1495 18.3175 14.8979 16.6284
2000 17.9288 18.1766 15.0504 16.6178

Writing D:\DEV\myPyCode\data\sea_rain_space.csv


In [289]:
pd.read_csv('D:\DEV\myPyCode\data\sea_rain_space.csv', sep=" ")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Kosmo\AppData\Local\Temp\ipykernel_14712\812264687.py:1: SyntaxWarning: invalid escape sequence '\D'
  pd.read_csv('D:\DEV\myPyCode\data\sea_rain_space.csv', sep=" ")


연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [291]:
pd.read_csv('D:\DEV\myPyCode\data\sea_rain.csv', index_col="연도")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Kosmo\AppData\Local\Temp\ipykernel_14712\4253411840.py:1: SyntaxWarning: invalid escape sequence '\D'
  pd.read_csv('D:\DEV\myPyCode\data\sea_rain.csv', index_col="연도")


동해       남해       서해       전체
연도                                      
1996  17.4629  17.2288  14.4360  15.9067
1997  17.4116  17.4092  14.8248  16.1526
1998  17.5944  18.0110  15.2512  16.6044
1999  18.1495  18.3175  14.8979  16.6284
2000  17.9288  18.1766  15.0504  16.6178

In [293]:
df_WH = pd.DataFrame({'Weight': [62, 67, 55, 74],
                      'Height': [165, 177, 160, 180]}, index=['ID_1', 'ID_2', 'ID_3', 'ID_4'] )
df_WH

Weight  Height
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

In [295]:
df_WH.index.name = 'User'
df_WH

Weight  Height
User                
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

In [297]:
# 체질량지수 bmi    몸무게 /  ( 키/100 ) ** 2

bmi = df_WH['Weight'] / (df_WH['Height'] / 100)**2
bmi

User
ID_1    22.773186
ID_2    21.385936
ID_3    21.484375
ID_4    22.839506
dtype: float64

In [299]:
df_WH['BMI'] = bmi
df_WH

Weight  Height        BMI
User                           
ID_1      62     165  22.773186
ID_2      67     177  21.385936
ID_3      55     160  21.484375
ID_4      74     180  22.839506

In [301]:
df_WH.to_csv('D:/DEV/myPyCode/data/save_DataFrame.csv')

In [303]:
!type D:\DEV\myPyCode\data\save_DataFrame.csv

User,Weight,Height,BMI
ID_1,62,165,22.77318640955005
ID_2,67,177,21.38593635289987
ID_3,55,160,21.484374999999996
ID_4,74,180,22.839506172839506


In [305]:
df_pr = pd.DataFrame({'판매가격':[2000, 3000, 5000, 10000],
                       '판매량':[32, 53, 40, 25]},
                       index=['P1001', 'P1002', 'P1003', 'P1004']) 
df_pr

판매가격  판매량
P1001   2000   32
P1002   3000   53
P1003   5000   40
P1004  10000   25

In [307]:
df_pr.index.name = '제품번호'
df_pr

판매가격  판매량
제품번호             
P1001   2000   32
P1002   3000   53
P1003   5000   40
P1004  10000   25

In [309]:
file_name = 'D:/DEV/myPyCode/data/save_DataFrame_cp949.txt'
df_pr.to_csv(file_name, sep=" ", encoding="cp949")

In [311]:
!type D:\DEV\myPyCode\data\save_DataFrame_cp949.txt

제품번호 판매가격 판매량
P1001 2000 32
P1002 3000 53
P1003 5000 40
P1004 10000 25
